### ISSUE TITLE
new roadmap

### ISSUE THREAD

**Issue by gammam** [pagopa/site-pagopa.gov.it#46]
Modificare la roadmap dando la possibilità di filtrare gli eventi in base alla sua sezione.
Ogni evento della roadmap potrà appartenere alle seguenti sezioni:

- Prodotto : Eventi legati principalmente ad evoluzioni tecnologiche 
- Servizio: eventi che portano beneficio agli utenti

Di seguito un esempio di file di configurazione da utilizzare.

```
it:
  - title: "Rilascio WISP 1.3"
    date: Q3
    year: 2017
    description: "Presentazione dell'interfaccia web per la selezione del PSP"
    category: Prodotto
  - title: "RAV di Agenzia delle Entrate-Riscossione"
    description: "I RAV emessi da Agenzia delle Entrate-Riscossione possono essere pagati su pagoPA"
    category: Servizio
    date: Q3
    year: 2017
  - title: "WISP 2.0"
    date: Q4
    year: 2017
    description: "Nuova interfaccia centralizzata per la selezione del PSP"
    category: Prodotto
  - title: "Specifiche POS fisico"
    description: "Presentazione di linee guida per l’integrazione di un POS fisico all’interno degli sportelli degli Enti Creditori"
    date: Q1
    year: 2018
    category: Prodotto
  - title: "Nuovo Avviso di Pagamento"
    description: "Introduzione dell’avviso di pagamento standard pagoPA, con design più intuitivo dei bollettini anche per i pagamenti nei punti fisici"
    category: Servizio
    date: Q2
    year: 2018
  - title: "Nuovo Wisp 2.0"
    description: "Adozione della nuova interfaccia da parte di tutte le pubbliche amministrazioni"
    date: Q1
    year: 2019
    category: Servizio
  - title: "Pagamento Bollo Auto"
    description: "Grazie alla collaborazione con ACI, è possibile pagare attraverso pagoPA anche i bolli in scadenza per i propri veicoli"
    category: Servizio
    date: Q1
    year: 2019
  - title: "BancomatPay"
    description: "Ai metodi di pagamento disponibili su pagoPA si aggiunge BancomatPay, ampliando le opzioni di scelta per i cittadini "
    category: Servizio
    date: Q2
    year: 2019
  - title: "Nuova Architettura"
    description: "Aggiornamento dell’infrastruttura, finalizzato a garantire massime prestazioni in vista dell’adesione di tutte le Pubbliche Amministrazioni al nodo dei pagamenti"
    category: Prodotto
    date: Q3
    year: 2019
  - title: "Nuove Specifiche MyBank"
    description: "Definizione di una nuova architettura per i pagamenti tramite MyBank"
    category: Prodotto
    date: Q3
    year: 2019
  - title: "Helpdesk aperto al pubblico"
    description: "Miglioramento del servizio di assistenza dedicato a pagoPA, ora disponibile anche per i cittadini "
    category: Servizio
    date: Q1
    year: 2020
  - title: "Postepay"
    description: "Postepay si aggiunge alla lista dei PSP aderenti a pagoPA"
    category: Servizio
    date: Q2
    year: 2020
  - title: "Personalizzazione del WISP (logo + lingua)"
    description: " Possibilità di personalizzare la landing page di pagoPA con un proprio logo e modificare la lingua di presentazione del WISP"
    category: Prodotto
    date: Q2
    year: 2020
  - title: "Pulsante unico MyBank"
    description: "Introduzione di un unico pulsante per tutti i pagamenti MyBank all’interno della sezione “Addebito in conto"
    category: Servizio
    date: Q2
    year: 2020
    todo: true
  - title: " Gestione convenzioni"
    description: "Gestione di convenzioni tra Ente Creditore e PSP, per consentire una riduzione dei costi di commissione a carico del cittadino"
    date: Q3
    year: 2020
    todo: true
  - title: "Wisp Light for Mobile -SDK deprecated"
    description: "Introduzione di una nuova interfaccia dedicata per l’esperienza mobile, che consente esclusivamente pagamenti con carta di utenti guest"
    date: Q3
    year: 2020
    todo: true
```
